# @package _global_

defaults:
  - override /hydra/sweeper: optuna

# choose metric which will be optimized by Optuna
optimized_metric: "mean_absolute_error"
optimized_mean: "cv_mean"

# here we define Optuna hyperparameter search
# it optimizes for value returned from function with @hydra.main decorator
# docs: https://hydra.cc/docs/plugins/optuna_sweeper/
hydra:
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    # storage URL to persist optimization results
    # for example, you can use SQLite if you set 'sqlite:///example.db'
    storage: null

    # name of the study to persist optimization results
    study_name: null

    # number of parallel workers
    n_jobs: 1

    # 'minimize' or 'maximize' the objective
    direction: minimize

    # total number of runs that will be executed
    n_trials: 200

    # choose Optuna hyperparameter sampler
    # docs: https://optuna.readthedocs.io/en/stable/reference/samplers/index.html
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: ${seed}
      consider_prior: true
      prior_weight: 1.0
      consider_magic_clip: true
      consider_endpoints: false
      n_startup_trials: 50
      n_ei_candidates: 10
      multivariate: false
      warn_independent_sampling: true

    # define range of hyperparameters
    params:
      pytorch_tabular_autoint.optimizer_lr: tag(log, interval(0.0001, 1))
      pytorch_tabular_autoint.optimizer_weight_decay: tag(log, interval(0.0000001, 0.001))
      pytorch_tabular_autoint.attn_embed_dim: choice(8, 16, 32)
      pytorch_tabular_autoint.num_heads: choice(2, 4, 8)
      pytorch_tabular_autoint.num_attn_blocks: choice(2, 3, 4, 5)
      pytorch_tabular_autoint.attn_dropouts: interval(0.0, 0.2)
      pytorch_tabular_autoint.has_residuals: choice(True, False)
      pytorch_tabular_autoint.embedding_dim: choice(4, 8, 16, 32)
      pytorch_tabular_autoint.embedding_dropout: interval(0.0, 0.4)
      pytorch_tabular_autoint.deep_layers: choice(False, True)
      pytorch_tabular_autoint.layers: choice("100-50", "200-100", "50-25", "128-64-32", "128-64")

