# CatBoost parameters available here:
# [https://catboost.ai/en/docs/references/training-parameters/]
name: catboost
loss_function: 'MAE'
learning_rate: 0.01
depth: 4
min_data_in_leaf: 15
max_leaves: 31
task_type: 'CPU'
verbose: 0
max_epochs: ${max_epochs}
patience: ${patience}
