# LightGBM parameters available here:
# [https://lightgbm.readthedocs.io/en/latest/Parameters.html]
name: lightgbm
objective: regression
boosting: gbdt
learning_rate: 0.05
num_leaves: 31
device: cpu
max_depth: -1
min_data_in_leaf: 10
feature_fraction: 0.9
bagging_fraction: 0.9
bagging_freq: 5
verbose: -1
metric: l1
max_epochs: ${max_epochs}
patience: ${patience}
