# Parameters for pytorch_tabular models available here:
# [https://github.com/manujosephv/pytorch_tabular/tree/main/pytorch_tabular/models]
name: pytorch_tabular_autoint
_target_: src.models.tabular.pytorch_tabular.autoint.PTAutoIntModel
task: regression
loss_type: L1Loss
input_dim: ${in_dim}
output_dim: ${out_dim}
optimizer_lr: 0.01
optimizer_weight_decay: 1.0e-06
scheduler_step_size: 100
scheduler_gamma: 0.8
embedding_dims: null
continuous_cols: null
categorical_cols: null
attn_embed_dim: 64
num_heads: 1
num_attn_blocks: 1
attn_dropouts: 0.1
has_residuals: true
embedding_dim: 64
embedding_dropout: 0.1
deep_layers: true
layers: 128-64-32
activation: ReLU
dropout: 0.0
use_batch_norm: false
batch_norm_continuous_input: false
attention_pooling: false
initialization: kaiming
