# Parameters for pytorch_tabular models available here:
# [https://github.com/manujosephv/pytorch_tabular/tree/main/pytorch_tabular/models]
name: pytorch_tabular_node
_target_: src.models.tabular.pytorch_tabular.node.PTNODEModel
task: regression
loss_type: "L1Loss"
input_dim: ${in_dim}
output_dim: ${out_dim}
optimizer_lr: 0.2
optimizer_weight_decay: 0.0
scheduler_step_size: 100
scheduler_gamma: 0.8
embedding_dims: null
continuous_cols: null
categorical_cols: null
num_layers: 1
num_trees: 512
additional_tree_output_dim: 4
depth: 6
choice_function: "entmax15"
bin_function: "sparsemoid"
max_features: null
input_dropout: 0.0
initialize_response: "normal"
initialize_selection_logits: "uniform"
threshold_init_beta: 1.0
threshold_init_cutoff: 1.0
embed_categorical: False
embedding_dropout: 0.0