# @package _global_

# specify here defaults
defaults:
  - _self_
  - experiment: train     # Global parameters of experiment
  - datamodule: tabular   # Information about dataset
  - trainer: gpu          # Run configuration for DNN models
  - callbacks: default    # Callbacks for DNN models
  - logger: none          # Loggers for DNN models
  - hydra: default.yaml   # Output paths for logs

  # Models options:
  # Linear:
  #   elastic_net
  # GBDT:
  #   xgboost
  #   lightgbm
  #   catboost
  # DNN:
  #   widedeep_tab_mlp
  #   widedeep_tab_net
  #   widedeep_ft_transformer
  #   widedeep_saint
  #   pytorch_tabular_autoint
  #   pytorch_tabular_tabnet
  #   pytorch_tabular_node
  #   nam
  #   danet
  - model: lightgbm

  - hparams_search: null  # Model-specific hyperparameters

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog
