# @package _global_

# specify here defaults
defaults:
  - _self_
  - experiment: train
  - datamodule: tabular
  # model options:
  # Linear: elastic_net
  # GBDT: xgboost, lightgbm, catboost
  # DNN: widedeep_tab_mlp, widedeep_tab_net, widedeep_ft_transformer, widedeep_saint
  - model: widedeep_saint
  - trainer: gpu
  - callbacks: default
  - logger: none

  - hparams_search: null

  - hydra: default.yaml

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog
