# @package _global_

# specify here defaults
defaults:
  - _self_
  - trainer: gpu
  - model: null
  - datamodule: tabular
  - callbacks: default
  - logger: none

  - experiment: null
  - hparams_search: null

  - hydra: default.yaml

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog
